//iconMap.js
import {
  Home,
  Edit2,
  FileText,
  Truck,
  Layers,
  Database,
  ShoppingCart,
  Warehouse,
  ArrowRightLeft,
  RotateCcw,
  Users,
  Globe,
  Ruler,
  Grid,
  Tag,
  BrickWall,
  HelpCircle,
  LogOut,
  ChevronDown,
  ChevronUp,
  User,
  CheckCircle,
  ScanEye,
  PackageOpen,
  Settings
} from 'lucide-react';

export const iconMap = {
  'home': Home,
  'edit': Edit2,
  'file-text': FileText,
  'truck': Truck,
  'layers': Layers,
  'database': Database,
  'shopping-cart': ShoppingCart,
  'warehouse': Warehouse,
  'arrow-right-left': ArrowRightLeft,
  'rotate-ccw': RotateCcw,
  'users': Users,
  'globe': Globe,
  'ruler': Ruler,
  'grid': Grid,
  'tag': Tag,
  'brick-wall': BrickWall,
  'help-circle': HelpCircle,
  'log-out': LogOut,
  'user': User,
  'check-circle': CheckCircle,
  'scan-eye': ScanEye,
  'package-open': PackageOpen,
  'settings': Settings
};