// File: src/components/PurchaseOrder/FooterPO.jsx
import React, { useEffect } from 'react';
import { Box, Typography, TextField } from '@mui/material';
import { useAuth } from '../../AuthContext';

const FooterPO = ({ setEnteredBy }) => {
  const { user } = useAuth();

  useEffect(() => {
    if (user?.name) {
      setEnteredBy(user.name); // Set enteredBy on mount
    }
  }, [user, setEnteredBy]);

  return (
    <Box sx={{ mt: 3 }}>
      <Typography variant="h6">PO Generated By</Typography>
        <TextField
          variant="filled"
          label="Generated By"
          value={user?.name || ''}
          fullWidth
          margin="normal"
          InputProps={{ readOnly: true }}
        />
    </Box>
  );
};

export default FooterPO;
